#logging="TRACE"
data-path="/opt/besu/data"
host-allowlist=["*"]

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]

# ws
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546

# xdns
Xdns-enabled=true

# permissions
permissions-nodes-config-file-enabled=false
permissions-nodes-config-file="/config/permissions_config.toml"

# bootnodes
#bootnodes=["enode://9cdd8e789a1ecd2b22896a91530fe1cd442a6b29f48bd7adfa755094ed3f99f56743d6350c8017ac7c7cd1c1872c392fbd14a4922a10578d46ad47290022d485@47.242.195.124:30303"]

# Discovery at boot is set to a list of static files, but will also discover new nodes should they be added
# static nodes
static-nodes-file="/config/static-nodes.json"
discovery-enabled=true
